### ISSUE TITLE
Errors with Vite 4.0

### ISSUE THREAD

**Issue by sketchpunk** [wesbos/vite-plugin-list-directory-contents#7]
Originally in vite 3 I used the following import to works
import { directoryPlugin } from 'vite-plugin-list-directory-contents/dist/plugin.js';

but now with vite 4 I get the following error
`failed to load config from C:\Files\personal\git\ossos_next\vite.config.js
error when starting dev server:
Error [ERR_REQUIRE_ESM]: require() of ES Module C:\Files\personal\git\ossos_next\node_modules\vite-plugin-list-directory-contents\dist\plugin.js from C:\Files\personal\git\ossos_next\vite.config.js not supported.
Instead change the require of plugin.js in C:\Files\personal\git\ossos_next\vite.config.js to a dynamic import() which is available in all CommonJS modules.
    at _require.extensions.<computed> [as .js] (file:///C:/Files/personal/git/ossos_next/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:62106:17)
    at Object.<anonymous> (C:\Files\personal\git\ossos_next\vite.config.js:89:21)
    at _require.extensions.<computed> [as .js] (file:///C:/Files/personal/git/ossos_next/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:62103:24)
    at loadConfigFromBundledFile (file:///C:/Files/personal/git/ossos_next/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:62111:21)
    at loadConfigFromFile (file:///C:/Files/personal/git/ossos_next/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:61969:34)
    at async resolveConfig (file:///C:/Files/personal/git/ossos_next/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:61590:28)
    at async createServer (file:///C:/Files/personal/git/ossos_next/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:60910:20)
    at async CAC.<anonymous> (file:///C:/Files/personal/git/ossos_next/node_modules/vite/dist/node/cli.js:729:24)`

using import { directoryPlugin } from 'vite-plugin-list-directory-contents'; 
gives me the following error

`failed to load config from C:\Files\personal\git\ossos_next\vite.config.js
error when starting dev server:
Error [ERR_REQUIRE_ESM]: require() of ES Module C:\Files\personal\git\ossos_next\node_modules\@wesbos\code-icons\index.js from C:\Files\personal\git\ossos_next\node_modules\vite-plugin-list-directory-contents\dist\plugin.cjs not supported.
Instead change the require of index.js in C:\Files\personal\git\ossos_next\node_modules\vite-plugin-list-directory-contents\dist\plugin.cjs to a dynamic import() which is available in all CommonJS modules.
    at _require.extensions.<computed> [as .js] (file:///C:/Files/personal/git/ossos_next/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:62106:17)
    at Object.<anonymous> (C:\Files\personal\git\ossos_next\node_modules\vite-plugin-list-directory-contents\dist\plugin.cjs:33:25)
    at _require.extensions.<computed> [as .js] (file:///C:/Files/personal/git/ossos_next/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:62106:17)
    at Object.<anonymous> (C:\Files\personal\git\ossos_next\vite.config.js:89:50)
    at _require.extensions.<computed> [as .js] (file:///C:/Files/personal/git/ossos_next/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:62103:24)
    at loadConfigFromBundledFile (file:///C:/Files/personal/git/ossos_next/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:62111:21)
    at loadConfigFromFile (file:///C:/Files/personal/git/ossos_next/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:61969:34)
    at async resolveConfig (file:///C:/Files/personal/git/ossos_next/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:61590:28)
    at async createServer (file:///C:/Files/personal/git/ossos_next/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:60910:20)
    at async CAC.<anonymous> (file:///C:/Files/personal/git/ossos_next/node_modules/vite/dist/node/cli.js:729:24)`

**Comment by wesbos** [comment]
Hey -thanks a ton. Any chance you can give me a little example of how you are using it? 

Also try update to the latest - I published a few versions this morning. I was playing with the ESM exports so that might be related

**Comment by wesbos** [comment]
I think the fix to this is to just add `"type": "module"` your package.json - but ideally it would just work with CJS as well..

**Comment by wesbos** [comment]
This should now just work regardless of config - try just upgrade the version and it should work. Reopen if not! :)
